# Generated by Django 5.2.13 on 2026-04-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('placa', models.CharField(help_text='Unique identifier for the vehicle', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('Gasoline', 'Gasolina'), ('Diesel', 'Diésel'), ('Gas', 'Gas')], help_text='Energy source type', max_length=20)),
                ('operational_status', models.CharField(choices=[('Operational', 'Operativo'), ('In Workshop', 'En Taller'), ('Under Review', 'Bajo Revisión'), ('Unfit', 'No Apto')], default='Operational', max_length=30)),
                ('current_km', models.FloatField(default=0.0, help_text='Last total recorded mileage')),
            ],
        ),
    ]
