# Generated by Django 6.0.4 on 2026-04-27 19:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('CORRECTIVE', 'Correctivo')], default='PREVENTIVE', max_length=20)),
                ('status', models.CharField(choices=[('PLANNING', 'Planificación'), ('EXECUTION', 'Ejecución'), ('CLOSURE', 'Cierre'), ('CANCELLED', 'Cancelada')], default='PLANNING', max_length=20, verbose_name='estadoActual')),
                ('start_date', models.DateTimeField(verbose_name='fechaInicio')),
                ('estimated_budget', models.FloatField(default=0.0, verbose_name='presupuestoEstimado')),
                ('man_hours', models.FloatField(default=0.0, verbose_name='horasHombre')),
                ('mechanic_observations', models.TextField(blank=True, null=True, verbose_name='observacionesTecnicas')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='fechaFin')),
                ('final_odometer', models.FloatField(blank=True, null=True, verbose_name='odometroCierre')),
                ('total_cost', models.FloatField(default=0.0, verbose_name='costoTotalReal')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('notif_type', models.CharField(choices=[('MILEAGE', 'Kilometraje'), ('LEGAL', 'Documentación')], default='MILEAGE', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('placa', models.CharField(help_text='Unique identifier for the vehicle', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('Gasoline', 'Gasolina'), ('Diesel', 'Diésel'), ('Gas', 'Gas')], help_text='Energy source type', max_length=20)),
                ('operational_status', models.CharField(choices=[('Operational', 'Operativo'), ('In Workshop', 'En Taller'), ('Under Review', 'Bajo Revisión'), ('Unfit', 'No Apto')], default='Operational', max_length=30)),
                ('current_km', models.FloatField(default=0.0, help_text='Last total recorded mileage')),
            ],
        ),
        migrations.CreateModel(
            name='PreventiveMaintenanceOrder',
            fields=[
                ('maintenanceorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.maintenanceorder')),
                ('scheduled_km', models.FloatField(verbose_name='kmProgramado')),
                ('service_type', models.CharField(max_length=100, verbose_name='tipoServicio')),
            ],
            bases=('vehicles.maintenanceorder',),
        ),
        migrations.CreateModel(
            name='OdometerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_reading', models.FloatField(help_text='Kilometraje registrado en el reporte')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exacta del reporte')),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('vehicle', models.ForeignKey(help_text='Vehículo al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='odometer_logs', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='maintenanceorder',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='vehicles.vehicle'),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Descripción detallada de la falla o incidente')),
                ('urgency_level', models.CharField(choices=[('Low', 'Leve'), ('Moderate', 'Moderada'), ('Critical', 'Crítica')], default='Low', max_length=20)),
                ('report_status', models.CharField(choices=[('Pending', 'Pendiente'), ('Under Review', 'En Revisión'), ('Resolved', 'Solucionado')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del reporte')),
                ('vehicle', models.ForeignKey(help_text='Vehículo asociado a la falla', on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_policy', models.CharField(help_text='Número de Póliza o Identificador único del documento', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('document_type', models.CharField(choices=[('Seguro', 'Seguro'), ('Revision Tecnica', 'Revision Tecnica'), ('Autorizacion', 'Autorizacion')], default='Seguro', max_length=30)),
                ('date_init', models.DateField(verbose_name='fechaInicio')),
                ('date_end', models.DateField(verbose_name='fechaFin')),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('document_file', models.FileField(blank=True, help_text='Soporte digital del documento (Solo formato PDF)', null=True, upload_to='documents/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('vehicle', models.ForeignKey(help_text='Vehículo asociado al documento', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date_init'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveMaintenanceOrder',
            fields=[
                ('maintenanceorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.maintenanceorder')),
                ('incident', models.OneToOneField(help_text='Vinculada a la orden de mantenimiento correctiva', on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='vehicles.incident')),
            ],
            bases=('vehicles.maintenanceorder',),
        ),
        migrations.CreateModel(
            name='MileageNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.notification')),
                ('preventive_order', models.ForeignKey(help_text='Asociada a la orden de mantenimiento preventivo', on_delete=django.db.models.deletion.CASCADE, related_name='mileage_notifications', to='vehicles.preventivemaintenanceorder')),
            ],
            bases=('vehicles.notification',),
        ),
    ]
