# Generated by Django 6.0.4 on 2026-04-27 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.notification')),
                ('document', models.ForeignKey(help_text='Asociada al documento legal próximo a vencer', on_delete=django.db.models.deletion.CASCADE, related_name='legal_notifications', to='vehicles.document')),
            ],
            bases=('vehicles.notification',),
        ),
    ]
