# Generated by Django 6.0.4 on 2026-04-26 23:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_policy', models.CharField(help_text='Unique identifier for the document', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('document_type', models.CharField(choices=[('Insurance', 'Seguro'), ('Technical Inspection', 'Revision Tecnica'), ('Authorization', 'Autorizacion')], default='Insurance', max_length=30)),
                ('date_init', models.DateField(verbose_name='fechaInicio')),
                ('date_end', models.DateField(verbose_name='fechaFin')),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('document_file', models.FileField(help_text='Soporte digital del documento (Solo formato PDF)', upload_to='documents/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('vehicle', models.ForeignKey(help_text='Vehículo asociado al documento', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date_init'],
            },
        ),
    ]
