# Generated by Django 6.0.4 on 2026-04-18 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdometerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_reading', models.FloatField(help_text='Kilometraje registrado en el reporte')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exacta del reporte')),
                ('vehicle', models.ForeignKey(help_text='Vehículo al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='odometer_logs', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
