# Generated by Django 6.0.4 on 2026-04-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_odometerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='odometerlog',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
