# Generated by Django 6.0.4 on 2026-04-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id_policy',
            field=models.CharField(help_text='Número de Póliza o Identificador único del documento', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
