# Generated by Django 5.2.13 on 2026-05-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_legalnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Está Activo?'),
        ),
    ]
