# Generated by Django 6.0.4 on 2026-04-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_document_id_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Seguro', 'Seguro'), ('Revision Tecnica', 'Revision Tecnica'), ('Autorizacion', 'Autorizacion')], default='Seguro', max_length=30),
        ),
    ]
