# Generated by Django 6.0.4 on 2026-05-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_photo',
            field=models.ImageField(blank=True, help_text='Physical image of the unit', null=True, upload_to='vehicles/'),
        ),
    ]
