# Generated by Django 5.2.13 on 2026-04-19 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_odometerlog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odometerlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Descripción detallada de la falla o incidente')),
                ('urgency_level', models.CharField(choices=[('Low', 'Leve'), ('Moderate', 'Moderada'), ('Critical', 'Crítica')], default='Low', max_length=20)),
                ('report_status', models.CharField(choices=[('Pending', 'Pendiente'), ('Under Review', 'En Revisión'), ('Resolved', 'Solucionado')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del reporte')),
                ('vehicle', models.ForeignKey(help_text='Vehículo asociado a la falla', on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='vehicles.vehicle')),
            ],
        ),
    ]
