# Generated by Django 5.2.13 on 2026-04-19 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_odometerlog_id_incident'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(verbose_name='fechaInicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='fechaFin')),
                ('total_cost', models.FloatField(default=0.0, verbose_name='costoTotal')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='observaciones')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='PreventiveMaintenanceOrder',
            fields=[
                ('maintenanceorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.maintenanceorder')),
                ('scheduled_km', models.FloatField(verbose_name='kmProgramado')),
                ('service_type', models.CharField(max_length=100, verbose_name='tipoServicio')),
            ],
            bases=('vehicles.maintenanceorder',),
        ),
        migrations.CreateModel(
            name='CorrectiveMaintenanceOrder',
            fields=[
                ('maintenanceorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.maintenanceorder')),
                ('incident', models.OneToOneField(help_text='Vinculada a la orden de mantenimiento correctiva', on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='vehicles.incident')),
            ],
            bases=('vehicles.maintenanceorder',),
        ),
    ]
