# Generated by Django 5.2.13 on 2026-04-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_maintenanceorder_preventivemaintenanceorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceorder',
            name='order_type',
            field=models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('CORRECTIVE', 'Correctivo')], default='PREVENTIVE', max_length=20),
        ),
    ]
