# Generated by Django 5.2.13 on 2026-04-26 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_maintenanceorder_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('notif_type', models.CharField(choices=[('MILEAGE', 'Kilometraje'), ('LEGAL', 'Documentación')], default='MILEAGE', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MileageNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.notification')),
                ('preventive_order', models.ForeignKey(help_text='Asociada a la orden de mantenimiento preventivo', on_delete=django.db.models.deletion.CASCADE, related_name='mileage_notifications', to='vehicles.preventivemaintenanceorder')),
            ],
            bases=('vehicles.notification',),
        ),
    ]
